---
sidebar: sidebar 
permalink: concepts/supported-storage-services.html 
keywords: storage, service, service definition, keystone STaaS services, 
summary: Los servicios de Keystone STaaS son compatibles con ONTAP y StorageGRID. 
---
= Almacenamiento compatible con Keystone
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Los servicios de Keystone STaaS admiten almacenamiento de archivos y bloques con ONTAP, almacenamiento de objetos con StorageGRID y Cloud Volumes ONTAP.

Keystone STaaS proporciona servicios estándar y opcionales para su almacenamiento.

* Servicios estándar de Keystone STaaS *: Los servicios estándar están incluidos en la suscripción básica y no se cobran por separado.

* Servicios complementarios de Keystone STaaS *: son servicios opcionales y de pago que brindan utilidades y beneficios adicionales además de los servicios de suscripción estándar de Keystone STaaS.

Los servicios Keystone STaaS se pueden utilizar al mismo tiempo.  Por ejemplo, una suscripción de almacenamiento en la nube puede tener el mismo plazo que las suscripciones de almacenamiento de archivos, bloques y objetos.  Se puede incluir un servicio en la nube en cualquier momento durante el plazo de servicio de una suscripción de almacenamiento existente.  Sin embargo, si no planea renovar una suscripción existente de archivos, bloques y objetos, no se podrá agregar una suscripción de almacenamiento en la nube durante los últimos 90 días de la suscripción.



== Servicios para almacenamiento de archivos, bloques y objetos

Los servicios Keystone STaaS para almacenamiento de archivos y bloques ONTAP y almacenamiento de objetos StorageGRID admiten múltiples funciones y protocolos, y se describen en la siguiente tabla:

|===
| Almacenamiento | Plataforma | Protocolos | Funciones compatibles 


 a| 
Almacenamiento de archivos
 a| 
ONTAP
 a| 
NFS y CIFS
 a| 
Funciones de ONTAP compatibles:

* FlexVol
* FlexGroup
* Copias instantáneas
* SnapMirror (asincrónico)
* SnapVault
* SnapLock Enterprise
* FabricPool/Nube en niveles
* SnapRestore
* FlexClone
* SnapCenter (la licencia está incluida, pero no es parte de los servicios de Keystone y no se garantiza su administración)
* Protección autónoma contra ransomware^1^




 a| 
Almacenamiento en bloque
 a| 
ONTAP
 a| 
FC e iSCSI
 a| 
Funciones de ONTAP compatibles:

* FlexVol
* FlexGroup
* Copias instantáneas
* SnapMirror (asincrónico)
* SnapVault
* SnapLock Enterprise
* FabricPool/Nube en niveles
* SnapRestore
* FlexClone
* SnapCenter (la licencia está incluida, pero no es parte de los servicios de Keystone y no se garantiza su administración)




 a| 
Almacenamiento de objetos
 a| 
StorageGRID
 a| 
S3
 a| 
Admite múltiples políticas de gestión del ciclo de vida de la información (ILM) en varios sitios^2^

|===

NOTE: ^1^ Para obtener información sobre la protección contra ransomware en ONTAP, consulte https://docs.netapp.com/us-en/ontap/anti-ransomware/index.html["Protección autónoma contra ransomware"^] .  ^2^ Cada sitio requiere una suscripción independiente.



== Servicios de almacenamiento en la nube

Keystone STaaS ofrece servicios de almacenamiento en la nube.  Keystone STaaS admite las capacidades de administración de datos de Cloud Volumes ONTAP en Amazon Web Services (AWS), Microsoft Azure y Google Cloud Platform.


NOTE: NetApp no proporciona los servicios de red, almacenamiento y computación basados en hiperescala que requiere Cloud Volumes ONTAP como parte de las suscripciones de Keystone STaaS; estas suscripciones deben adquirirse directamente de los proveedores de servicios de nube hiperescalar.
