---
sidebar: sidebar 
permalink: installation/linux-installation.html 
keywords: Linux installation Keystone, Linux Collector installation 
summary: Instale el software Keystone Collector desde el repositorio de software YUM. 
---
= Instalar Keystone Collector en sistemas Linux
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Puede instalar el software Keystone Collector en un servidor Linux usando un RPM o un paquete Debian.  Siga los pasos de instalación según su distribución de Linux.

[role="tabbed-block"]
====
.Usando RPM
--
. Conéctese por SSH al servidor Keystone Collector y elévelo a `root` privilegio.
. Importe la firma pública de Keystone :
`# rpm --import https://keystone.netapp.com/repo1/RPM-GPG-NetApp-Keystone-20251020`
. Asegúrese de que se ha importado el certificado público correcto comprobando la huella digital de Keystone Billing Platform en la base de datos RPM:
`# rpm -qa gpg-pubkey --qf '%{Description}'|gpg --show-keys --fingerprint` La huella dactilar correcta tiene este aspecto:
`9297 0DB6 0867 22E7 7646 E400 4493 5CBB C9E9 FEDC`
. Descarga el `keystonerepo.rpm` archivo:
`curl -O https://keystone.netapp.com/repo1/keystonerepo.rpm`
. Verifique la autenticidad del archivo:
`rpm --checksig -v keystonerepo.rpm` La firma de un archivo auténtico tiene este aspecto:
`Header V4 RSA/SHA512 Signature, key ID c9e9fedc: OK`
. Instale el archivo del repositorio de software YUM:
`# yum install keystonerepo.rpm`
. Cuando se instala el repositorio de Keystone , instala el paquete keystone-collector a través del administrador de paquetes YUM:
+
`# yum install keystone-collector`

+
Para Red Hat Enterprise Linux 9, ejecute el siguiente comando para instalar el paquete keystone-collector:
`# yum install keystone-collector-rhel9`



--
.Usando Debian
--
. Conéctese por SSH al servidor Keystone Collector y elévelo a `root` privilegio.
`sudo su`
. Descargar el `keystone-sw-repo.deb` archivo:
`curl -O https://keystone.netapp.com/downloads/keystone-sw-repo.deb`
. Instale el archivo del repositorio de software de Keystone :
`# dpkg -i keystone-sw-repo.deb`
. Actualizar la lista de paquetes:
`# apt-get update`
. Cuando se instale el repositorio de Keystone , instale el paquete keystone-collector:
`# apt-get install keystone-collector`


--
====

NOTE: Una vez completada la instalación, puede utilizar la utilidad de interfaz de usuario del terminal (TUI) de administración de Keystone Collector para realizar las actividades de configuración y supervisión.  Puede utilizar varios controles del teclado, como Enter y las teclas de flecha, para seleccionar las opciones y navegar por esta TUI.  Verlink:../installation/configuration.html["Configurar Keystone Collector"] ylink:../installation/monitor-health.html["Monitorear la salud del sistema"] para información.
