---
sidebar: sidebar 
permalink: dark-sites/install-collector.html 
keywords: install, keystone, collector, private, mode, vmware vsphere, linux, deploy, debian, rpm file 
summary: Complete unos pocos pasos para instalar Keystone Collector en un entorno que no tenga acceso a Internet, también conocido como _sitio oscuro_ o _modo privado_. 
---
= Instalar Keystone Collector en modo privado
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Complete unos pocos pasos para instalar Keystone Collector en un entorno que no tenga acceso a Internet, también conocido como _sitio oscuro_ o _modo privado_.  Este tipo de instalación es perfecta para sus sitios seguros.

Puede implementar Keystone Collector en sistemas VMware vSphere o instalarlo en sistemas Linux, según sus requisitos.  Siga los pasos de instalación que correspondan a su opción seleccionada.



== Implementar en VMware vSphere

Siga estos pasos:

. Descargue el archivo de plantilla OVA desde https://keystone.netapp.com/downloads/KeystoneCollector-latest.ova["Portal web de NetApp Keystone"] .
. Para conocer los pasos para implementar el recopilador Keystone con el archivo OVA, consulte la secciónlink:../installation/vapp-installation.html#deploying-the-ova-template["Implementación de la plantilla OVA"] .




== Instalar en Linux

El software Keystone Collector se instala en el servidor Linux utilizando los archivos .deb o .rpm proporcionados, según la distribución de Linux.

Siga estos pasos para instalar el software en su servidor Linux:

. Descargue o transfiera el archivo de instalación de Keystone Collector al servidor Linux:
+
`keystone-collector-<version>.noarch.rpm`

. Abra una terminal en el servidor y ejecute los siguientes comandos para comenzar la instalación.
+
** *Usando el paquete Debian*
+
`dpkg -i keystone-collector_<version>_all.deb`

** *Usando archivo RPM*
+
`yum install keystone-collector-<version>.noarch.rpm`

+
o

+
`rpm -i keystone-collector-<version>.noarch.rpm`



. Ingresar `y` cuando se le solicite instalar el paquete.

