---
sidebar: sidebar 
permalink: dark-sites/requirements.html 
keywords: installation, private mode, requirement, vmware vsphere, linux, networking,disk, space 
summary: Antes de instalar Keystone Collector en un entorno sin acceso a Internet, también conocido como _sitio oscuro_ o _modo privado_, asegúrese de que sus sistemas estén preparados con el software necesario y cumplan con todos los requisitos previos requeridos. 
---
= Prepárese para la instalación en modo privado
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Antes de instalar Keystone Collector en un entorno sin acceso a Internet, también conocido como _sitio oscuro_ o _modo privado_, asegúrese de que sus sistemas estén preparados con el software necesario y cumplan con todos los requisitos previos requeridos.



== Requisitos para VMware vSphere

* Sistema operativo: servidor VMware vCenter y ESXi 6.7 o posterior
* Núcleo: 1 CPU
* RAM: 2 GB
* Espacio en disco: 20 GB vDisk




== Requisitos para Linux

* Sistema operativo (elija uno):
+
** Red Hat Enterprise Linux (RHEL) 8.6 o cualquier versión posterior de la serie 8.x
** Red Hat Enterprise Linux 9.0 o versiones posteriores
** Debian 12


* Núcleo: 2 CPU
* RAM: 4 GB
* Espacio en disco: 50 GB vDisk
+
** Al menos 2 GB libres en `/var/lib/`
** Al menos 48 GB libres en `/opt/netapp`




El mismo servidor también debe tener instalados los siguientes paquetes de terceros.  Si están disponibles a través del repositorio, estos paquetes se instalarán automáticamente como requisitos previos:

* RHEL 8.6+ (8.x)
+
** python3 >=v3.6.8, python3 \<=v3.9.13
** hombre de pod
** llamada de socorro
** yum-utils
** Bloqueo de versión del complemento DNF de Python3


* RHEL 9,0+
+
** python3 >= v3.9.0, python3 \<= v3.9.13
** hombre de pod
** llamada de socorro
** yum-utils
** Bloqueo de versión del complemento DNF de Python3


* Debian v12
+
** python3 >= v3.9.0, python3 \<= v3.12.0
** hombre de pod
** informe de sos






== Requisitos de red

Los requisitos de red para Keystone Collector incluyen lo siguiente:

* Active IQ Unified Manager (Unified Manager) 9.10 o posterior, configurado en un servidor con la funcionalidad API Gateway habilitada.
* El servidor de Unified Manager debe ser accesible a través del servidor Keystone Collector en el puerto 443 (HTTPS).
* Se debe configurar una cuenta de servicio con permisos de usuario de aplicación para Keystone Collector en el servidor Unified Manager.
* No se requiere conectividad a Internet externa.
* Cada mes, exporte un archivo desde Keystone Collector y envíelo por correo electrónico al equipo de soporte de NetApp . Para obtener más información sobre cómo contactar con el equipo de soporte, consulte link:../concepts/support-services.html["Obtenga ayuda con Keystone"].

