---
sidebar: sidebar 
permalink: release-notes/known-limitations.html 
keywords: limitations, known limitations in Keystone STaaS 
summary: Las limitaciones conocidas identifican plataformas, dispositivos o funciones que no son compatibles con esta versión del producto o que no interoperan correctamente con él.  Revise estas limitaciones cuidadosamente. 
---
= Limitaciones conocidas en Keystone STaaS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Las limitaciones conocidas identifican plataformas, dispositivos o funciones que no son compatibles con los servicios o componentes de Keystone STaaS, o que no interoperan correctamente.  Revise estas limitaciones cuidadosamente.



== Limitaciones de Keystone Collector



=== Error de autenticación de Keystone Collector con StorageGRID SSO habilitado

Keystone Collector no admite la medición cuando el sistema StorageGRID tiene habilitado el inicio de sesión único (SSO).  El siguiente mensaje de error se muestra en los registros:

`panic: json: cannot unmarshal object into Go struct field AuthResponse.data of type string`

Ver artículo de la base de conocimientoslink:https://kb.netapp.com/hybrid/Keystone/Collector/Keystone_Collector_fails_to_authenticate_with_StorageGRID_in_SSO_Mode["Keystone Collector no puede autenticarse con StorageGRID en modo SSO"^] para información y resolución.



=== Keystone Collector no puede iniciarse en vSphere 8.0 Update 1

No se puede encender una máquina virtual (VM) de Keystone Collector con VMware vSphere versión 8.0 Update 1 y se muestra el siguiente mensaje de error:

`Property 'Gateway' must be configured for the VM to power on.`

Ver artículo de la base de conocimientoslink:https://kb.netapp.com/hybrid/Keystone/Collector/Keystone_Collector_fails_to_start_on_vSphere_8.0_U1["Keystone Collector no se inicia en vSphere 8.0 U1"^] para información y resolución.



=== No se puede generar un paquete de soporte a través de Kerberos

Si el directorio de inicio de Keystone Collector se monta sobre NFSv4 mediante Kerberos, no se genera el paquete de soporte y se muestra el siguiente mensaje de error:

`subprocess.CalledProcessError: Command '['sosreport', '--batch', '-q', '--tmp-dir', '/home/<user>']' returned non-zero exit status 1.`

Ver artículo de la base de conocimientos https://kb.netapp.com/hybrid/Keystone/Collector/Keystone_Collector_fails_to_generate_support_bundle_on_Kerberized_home_directory["Keystone Collector no genera un paquete de soporte en el directorio de inicio kerberizado"^] para información y resolución.



=== Keystone Collector no puede comunicarse con hosts dentro de un rango de red específico

Keystone Collector no puede comunicarse con dispositivos dentro del rango de red 10.88.0.0/16 cuando el `ks-collector` El servicio está en ejecución.  Ver artículo de la base de conocimientoslink:https://kb.netapp.com/hybrid/Keystone/Collector/Keystone_Collector_container_conflict_with_customer_network["Conflicto del contenedor de Keystone Collector con la red del cliente"^] para información y resolución.



=== Keystone Collector no puede verificar el certificado CA SSL raíz del cliente

Si la inspección SSL/TLS está habilitada en el firewall de borde en un entorno para inspeccionar el tráfico SSL/TLS, Keystone Collector no puede establecer una conexión HTTPS, porque el certificado CA raíz del cliente no es confiable.

Para obtener más información y resolución, consultelink:..//installation/configuration.html#trust-a-custom-root-ca["Confíe en una CA raíz personalizada"^] o artículo de la base de conocimientoslink:https://kb.netapp.com/hybrid/Keystone/Collector/Keystone_Collector_cannot_verify_Customer_Root_SSL_CA_certificate["Keystone Collector no puede verificar el certificado CA SSL raíz del cliente"^] .
